# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             http://loverszhaokai.github.io
paginate:            5
markdown:            kramdown

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0


# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
auto_ids:       true
footnote_nr:    1
entity_output:  as_char
toc_levels:     1..6
smart_quotes:   lsquo,rsquo,ldquo,rdquo
enable_coderay: false

coderay:
coderay_wrap:              div
coderay_line_numbers:      inline
coderay_line_number_start: 1
coderay_tab_width:         4
coderay_bold_every:        10
coderay_css:               style
